[package]
name = "bfb"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
clap = { version = "4.1.6", features = ["derive"] }
ctrlc = "3.2.5"
futures = "0.3.25"
indicatif = "0.17.3"
qdrant-client = "1.1.0"
rand = "0.8.5"
tokio = { version = "~1.25", features = ["full"] }
uuid = { version = "1.3.0", features = ["serde", "v4"] }
