[package]
name = "bfb"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.65"
clap = { version = "4.0.17", features = ["derive"] }
ctrlc = "3.2.3"
futures = "0.3.24"
indicatif = "0.17.1"
qdrant-client = "0.10.7"
rand = "0.8.5"
tokio = { version = "~1.21", features = ["full"] }
uuid = "1.2.1"
