[package]
name = "bfb"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.3.0", features = ["derive"] }
ctrlc = "3.3.1"
futures = "0.3.28"
indicatif = "0.17.3"
memmap2 = "0.6.1"
qdrant-client = "1.2.0"
rand = "0.8.5"
tokio = { version = "1.28.1", features = ["full"] }
uuid = { version = "1.3.3", features = ["serde", "v4"] }
